### ISSUE TITLE
Url to documentation is invalid

### ISSUE THREAD

**Issue by vlcinsky** [seznam/python-fastjsonschema#1]
The url http://opensource.seznam.cz/python-fastjsonschema/ does not exists.

**Comment by horejsek** [comment]
Thanks for notifying. Fixed. :-)

**Comment by vlcinsky** [comment]
@horejsek Does not seem to be fixed:

	$ dig +short seznam.cz
	77.75.79.39
	$ dig +short opensource.seznam.cz

It seems the DNS record is not publicly accessible.

Tested from two distinct servers.

**Comment by horejsek** [comment]
In README and description is new URL. :-)
I don't work at Seznam anymore but I found they just moved it to this standard location: https://seznam.github.io/python-fastjsonschema/

**Comment by vlcinsky** [comment]
Great, now it works. Thanks.
