### ISSUE TITLE
Failed to validate against unicode and long

### ISSUE THREAD

**Issue by chiuup** [seznam/python-fastjsonschema#10]
In the JSON_TYPE_TO_PYTHON_TYPE mapping, "string" does not include unicode type for Python2. It's not able to validate against JSON objects with unicode strings. 

Also "number" and "integer" does not include type "long" in Python2.

**Comment by horejsek** [comment]
Python 2 is not supported at all without any planing to do that.

I recommend to switch to Python 3 as Python 2 will retire very soon...
