### ISSUE TITLE
Underscores stripped from object property keys in schema

### ISSUE THREAD

**Issue by j616** [seznam/python-fastjsonschema#5]
I have a schema with something similar to the following in it.
```json
{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "type": "object",
 "properties": {
  "object_key": {
   "title": "My Object Entry",
   "description": "An object entry that must always have a value of 'foo'.",
   "type": "string",
   "enum":[
    "foo"
   ]
  }
}
```
This will match against a key called `objectkey` but reject one called `object_key`. I'm also seeing a schema with a key `@_ns` match against a document containing `ns` but not `@_ns`.

For the same reason, the examples at https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties will not work because of the property `street_name`.

**Comment by horejsek** [comment]
Thanks for report, will be fixed in next version!
