### ISSUE TITLE
AnyOf together with pattern matching not working

### ISSUE THREAD

**Issue by icepol** [seznam/python-fastjsonschema#6]
Hi, pls. for this example:
```
import fastjsonschema

schema = {
    'type': 'object',
    'properties': {
        'hash': {
            'anyOf': [
                {
                    'type': 'string',
                    'pattern': '^AAA'
                },
                {
                    'type': 'string',
                    'pattern': '^BBB'
                }
            ]
        }
    }
}

validator = fastjsonschema.compile(schema)

data = {
    'hash': 'AAAXXX',
}

validator(data)
```

**Expected**: data are valid against the schema.
**Actual**: `fastjsonschema.exceptions.JsonSchemaException: data.hash must be valid by one of anyOf definition`
**Python version**: 3.6
**fastjsonschema version**: 1.2

Looks like `anyOf` together with `pattern` matching is not working as expected.

**Comment by horejsek** [comment]
Thanks for reporting! Have you found any other bug in new version? :-)

**Comment by icepol** [comment]
thanks for the fix :)
nope, all other is working just fine.
